name: finway_app
description: Fintech credit navigator prototype
version: 0.3.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.20.2
  shared_preferences: ^2.2.3
  crypto: ^3.0.3

flutter:
  uses-material-design: true
